id: P003299
initial_creation_type: ocr
source_metadata:
  id: bdr:W322
  title: དཔལ་ཆོས་ཀྱི་གྲགས་པས་མཛད་པའི་ཚད་མ་རྣམ་འགྲེལ་གྱི་རང་འགྲེལ་ལས་རང་དོན་རྗེས་དཔག་གི་སྐོར་རྩ་འགྲེལ་ཤན་སྦྱར།
  author: ''
  volumes:
    485da5b7f1044302bdfa16fae94c3a22:
      image_group_id: I1KG16162
      title: ''
      volume_number: 1
      total_pages: 260
      base_file: v001.txt
