id: opecha:P003299
initial_creation_type: ocr
source_metadata:
  id: bdr:W322
  title: དཔལ་ཆོས་ཀྱི་གྲགས་པས་མཛད་པའི་ཚད་མ་རྣམ་འགྲེལ་གྱི་རང་འགྲེལ་ལས་རང་དོན་རྗེས་དཔག་གི་སྐོར་རྩ་འགྲེལ་ཤན་སྦྱར།
  volume: ''
  author: ''
